# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swarmSearchDialog.ui'
#
# Created: Tue Aug 11 13:59:06 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_swarmSearchDialog(object):
    def setupUi(self, swarmSearchDialog):
        swarmSearchDialog.setObjectName("swarmSearchDialog")
        swarmSearchDialog.resize(355, 350)
        self.btnbx_CancelOK = QtWidgets.QDialogButtonBox(swarmSearchDialog)
        self.btnbx_CancelOK.setGeometry(QtCore.QRect(-60, 310, 341, 32))
        self.btnbx_CancelOK.setOrientation(QtCore.Qt.Horizontal)
        self.btnbx_CancelOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnbx_CancelOK.setObjectName("btnbx_CancelOK")
        self.lbl_swarmSearch = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_swarmSearch.setGeometry(QtCore.QRect(60, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_swarmSearch.setFont(font)
        self.lbl_swarmSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_swarmSearch.setWordWrap(True)
        self.lbl_swarmSearch.setObjectName("lbl_swarmSearch")
        self.lbl_masterID = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_masterID.setGeometry(QtCore.QRect(70, 40, 141, 20))
        self.lbl_masterID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_masterID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_masterID.setObjectName("lbl_masterID")
        self.masterID_spinBox = QtWidgets.QSpinBox(swarmSearchDialog)
        self.masterID_spinBox.setGeometry(QtCore.QRect(230, 40, 60, 27))
        self.masterID_spinBox.setMaximum(255)
        self.masterID_spinBox.setProperty("value", 101)
        self.masterID_spinBox.setObjectName("masterID_spinBox")
        self.lbl_searchEnum = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchEnum.setGeometry(QtCore.QRect(70, 80, 141, 20))
        self.lbl_searchEnum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchEnum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchEnum.setObjectName("lbl_searchEnum")
        self.searchAlgo_spinBox = QtWidgets.QSpinBox(swarmSearchDialog)
        self.searchAlgo_spinBox.setGeometry(QtCore.QRect(230, 80, 60, 27))
        self.searchAlgo_spinBox.setMinimum(1)
        self.searchAlgo_spinBox.setMaximum(2)
        self.searchAlgo_spinBox.setObjectName("searchAlgo_spinBox")
        self.lbl_searchArea = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchArea.setGeometry(QtCore.QRect(140, 120, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_searchArea.setFont(font)
        self.lbl_searchArea.setToolTip("")
        self.lbl_searchArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchArea.setObjectName("lbl_searchArea")
        self.lbl_searchArea_Length = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchArea_Length.setGeometry(QtCore.QRect(50, 230, 131, 20))
        self.lbl_searchArea_Length.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchArea_Length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchArea_Length.setObjectName("lbl_searchArea_Length")
        self.lbl_searchArea_Width = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchArea_Width.setGeometry(QtCore.QRect(60, 270, 121, 20))
        self.lbl_searchArea_Width.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchArea_Width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchArea_Width.setObjectName("lbl_searchArea_Width")
        self.lbl_searchArea_Lat = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchArea_Lat.setGeometry(QtCore.QRect(20, 150, 191, 20))
        self.lbl_searchArea_Lat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchArea_Lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchArea_Lat.setObjectName("lbl_searchArea_Lat")
        self.lbl_searchArea_Lon = QtWidgets.QLabel(swarmSearchDialog)
        self.lbl_searchArea_Lon.setGeometry(QtCore.QRect(10, 180, 201, 20))
        self.lbl_searchArea_Lon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_searchArea_Lon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_searchArea_Lon.setObjectName("lbl_searchArea_Lon")
        self.doubleSpinBox_Lat = QtWidgets.QDoubleSpinBox(swarmSearchDialog)
        self.doubleSpinBox_Lat.setGeometry(QtCore.QRect(230, 150, 111, 27))
        self.doubleSpinBox_Lat.setDecimals(6)
        self.doubleSpinBox_Lat.setMinimum(-90.0)
        self.doubleSpinBox_Lat.setMaximum(90.0)
        self.doubleSpinBox_Lat.setSingleStep(1e-06)
        self.doubleSpinBox_Lat.setProperty("value", 35.720474)
        self.doubleSpinBox_Lat.setObjectName("doubleSpinBox_Lat")
        self.doubleSpinBox_Lon = QtWidgets.QDoubleSpinBox(swarmSearchDialog)
        self.doubleSpinBox_Lon.setGeometry(QtCore.QRect(230, 180, 111, 27))
        self.doubleSpinBox_Lon.setDecimals(6)
        self.doubleSpinBox_Lon.setMinimum(-180.0)
        self.doubleSpinBox_Lon.setMaximum(180.0)
        self.doubleSpinBox_Lon.setSingleStep(1e-06)
        self.doubleSpinBox_Lon.setProperty("value", -120.77481)
        self.doubleSpinBox_Lon.setObjectName("doubleSpinBox_Lon")
        self.doubleSpinBox_Length = QtWidgets.QDoubleSpinBox(swarmSearchDialog)
        self.doubleSpinBox_Length.setGeometry(QtCore.QRect(200, 230, 141, 27))
        self.doubleSpinBox_Length.setDecimals(0)
        self.doubleSpinBox_Length.setMinimum(1.0)
        self.doubleSpinBox_Length.setMaximum(37950.0)
        self.doubleSpinBox_Length.setSingleStep(1.0)
        self.doubleSpinBox_Length.setProperty("value", 900.0)
        self.doubleSpinBox_Length.setObjectName("doubleSpinBox_Length")
        self.doubleSpinBox_Width = QtWidgets.QDoubleSpinBox(swarmSearchDialog)
        self.doubleSpinBox_Width.setGeometry(QtCore.QRect(200, 270, 141, 27))
        self.doubleSpinBox_Width.setDecimals(0)
        self.doubleSpinBox_Width.setMinimum(1.0)
        self.doubleSpinBox_Width.setMaximum(37950.0)
        self.doubleSpinBox_Width.setSingleStep(1.0)
        self.doubleSpinBox_Width.setProperty("value", 600.0)
        self.doubleSpinBox_Width.setObjectName("doubleSpinBox_Width")

        self.retranslateUi(swarmSearchDialog)
        self.btnbx_CancelOK.accepted.connect(swarmSearchDialog.accept)
        self.btnbx_CancelOK.rejected.connect(swarmSearchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(swarmSearchDialog)

    def retranslateUi(self, swarmSearchDialog):
        _translate = QtCore.QCoreApplication.translate
        swarmSearchDialog.setWindowTitle(_translate("swarmSearchDialog", "Dialog"))
        self.lbl_swarmSearch.setText(_translate("swarmSearchDialog", "Swarm Search Parameters"))
        self.lbl_masterID.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>ID of UAV to be Master Searcher</p></body></html>"))
        self.lbl_masterID.setText(_translate("swarmSearchDialog", "Master Searcher ID:"))
        self.lbl_searchEnum.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>Enumeration of search algorithm to run</p></body></html>"))
        self.lbl_searchEnum.setText(_translate("swarmSearchDialog", "Search Algo to run:"))
        self.lbl_searchArea.setText(_translate("swarmSearchDialog", "Search Area:"))
        self.lbl_searchArea_Length.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>Distance between left and right bound of the search area</p></body></html>"))
        self.lbl_searchArea_Length.setText(_translate("swarmSearchDialog", "Search Length (X):"))
        self.lbl_searchArea_Width.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>Distance between top and bottom bound of search area</p></body></html>"))
        self.lbl_searchArea_Width.setText(_translate("swarmSearchDialog", "Search Width (Y):"))
        self.lbl_searchArea_Lat.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>Latitude of the bottom point of search area</p></body></html>"))
        self.lbl_searchArea_Lat.setText(_translate("swarmSearchDialog", "Bottom left point Latitude:"))
        self.lbl_searchArea_Lon.setToolTip(_translate("swarmSearchDialog", "<html><head/><body><p>Longitude of the bottom point of search area</p></body></html>"))
        self.lbl_searchArea_Lon.setText(_translate("swarmSearchDialog", "Bottom left point Longitude:"))
        self.doubleSpinBox_Length.setSuffix(_translate("swarmSearchDialog", " meters"))
        self.doubleSpinBox_Width.setSuffix(_translate("swarmSearchDialog", " meters"))

